#!/bin/bash
#
# TITLE: harvest
# AUTHOR: Boardleash (Derek)
# DATE: Saturday, July 27 2024
#
#
#                                            :+######=
#                                        ::.:%@%%%%%#-
#                                     :*@%%%%%%%%%%%#=
#                                    :#%%@@@#%#++*%#%%%%*-
#                                    :%%@@%*=*+#+-*=+%@%%@
#                                     -#%%%+===----==#@@@+
#                                       :--++*++====+@#-:
#                                          -+===--::
#                                     :------==-=-------=+-
#                                  :=+=======+=------=-=-+*=
#    :.:::-+=:                    *%+==--=+--====-=-:-+---##-
#  -----=--####=                +###%%+-=#%*+--=:=+::-+*####**
# :-+:---=-***#**##*-::     :*#%####%%%%%%#*#*=*-+#+-*####%####-
#:-----=-:-+####*#*#%####*#####%%###%##%#%#******########%%###%@#%%#-:.:.:-=========:.:::
#:----:::--*%%#######%##*######%%###%%%%###*****#########%%%%##%#%%##*#+%%#%#######+::::--:
# :-=-----:..::=#%######+#*#%%%%%%%+-=%%###**############@%%%%%%%%%#%**#%##%###%#%%=-:--::
#   :=-:.:::        :+*%#*#%%%+      -%%##%#############%#.:#%%%%%%%%#*%%%#%%%#%%@%--::---:
#                        :           -%%###%############%*     ---+***+**+=:...::  :----:
#                                    -%%###%############%-                          :--:-:
#                                    -%####%#############:                           ::-::
#                                    -%####%###########**:
#                                    =%%###%##########***
#                                    =%%##############*#*-
#                                    =%%*#%#*############+
#                                    =#%####*#############
#                                    =#%#%%###############-
#                                    =%#%%%###############+
#                                   :*%%%%%%####%##########
#                                   -#%#%%%################:
#                                   =#%%%%%%###############-
#                                   =%%%%%%%%###%##########*
#                                  :*%%%%%%%%%%%%%%%%%%%#%%#:
#                                  :+#%%#%%%%%%%%%%%%%%%#*%+
#                                  :=+%%*%%%##%+%%%##%%#++#-
#                                   -=+#=#%#+**#%%#=+%%#+-=:
#                                      ::*#*=++#%%*=+*#+=-
#                                       :=+-+==*%+==--=-=-
#                                        ::.---====-=:::::
#                                           ::-=-::::::
#                                             -+
#                                             -=
#                                             --
#                                             --
#                                             :-
#                                             --
#                                             --
#                                             --
#                                              :
# A script that will pull certain host, hardware and user information on a host.
# This information is output to a hidden file called ".harvest" within the /tmp/ directory.
# Tested on RHEL 9 and CentOS Stream 9 Workstation and Server (with GUI) VM images.
# This can be ran with escalated privileges if desired.

# Set up some formatting variables.
blinkcyan='\033[6;96m'
grn='\033[1;92m'
iorng='\033[3;93m'
orng='\033[1;33m'
noc='\033[0m'

# Capture all output and formatting to be viewed via terminal only (cat).
exec > >(tee -i /tmp/.harvest)

# Set up animation function.
pumpkin() {
	echo -e "
	          "$grn" ****
                 ****
                ****"$noc"
          "$orng"+==="$noc""$grn"*****"$noc""$orng"===...
      ++=======+"$noc""$grn"***"$noc""$orng"+=======...
    ++========================...
   ++============================...
  ++===+"$noc""$blinkcyan"#"$noc""$orng"*==============*"$noc""$blinkcyan"#"$noc""$orng"++=======...
  +==+*"$noc""$blinkcyan"###"$noc""$orng"+===========++"$noc""$blinkcyan"###"$noc""$orng"*+========...
  +=+"$noc""$blinkcyan"######"$noc""$orng"*+===++====+"$noc""$blinkcyan"######"$noc""$orng"*+=====...
  +===++++====+"$noc""$blinkcyan"###"$noc""$orng"+=====++++==========...
  +==========+*"$noc""$blinkcyan"####"$noc""$orng"*===============+=...
  ++===++====*+====++===++====+++=======...
  ++==++"$noc""$blinkcyan"#######################"$noc""$orng"+======...
   +===+*"$noc""$blinkcyan"#####################"$noc""$orng"*+=====...
    ++==+"$noc""$blinkcyan"###"$noc""$orng"**"$noc""$blinkcyan"#####"$noc""$orng"**"$noc""$blinkcyan"####"$noc""$orng"*+"$noc""$blinkcyan"###"$noc""$orng"+====+=...
      +========+=================...
        +===========+==========...
            +++==+++++==+++"$noc""
	echo
	echo -e ""$iorng"     May the harvest be bountiful..."$noc""
	echo
}

# Set up introduction function.
intro() {
	echo -e ""$orng"       Greetings! Is it time?
       Your harvest lies below.
     Should you want to gather it, 
      check your /tmp/ directory."$noc""
  sleep 5s
}

# Set up the harvester function.
harvest() {
	echo
	echo "Who is harvesting?: "$USER""
	echo "
#################
### HOST INFO ###
#################"
	echo
	hostnamectl | grep "Static hostname\|Operating System\|Kernel\|Hardware Model"
	echo "
#####################
### HARDWARE INFO ###
#####################"
	echo
	lscpu | grep "Model name\|Virtualization"
	echo "
###########
### RAM ###
###########"
	echo
	lsmem | grep "Total"
	echo "
###############
### STORAGE ###
###############"
	echo
	wheat=$(df -h | awk '{printf "%-20s %-20s %-20s\n", $1, $2, $5}')
	echo "$wheat"
	echo
	corn=$(lsblk | awk '{printf "%-20s %-20s %-20s\n", $1, $4, $6}')
	echo "$corn"; echo "
#####################################################
### LOAD AVG (1 minute, 5 minutes and 15 minutes) ###
#####################################################"
	echo
	echo "     For reference, 1.00 = 100% load average."
	echo
	awk '{printf "%-10s %-10s %-10s\n", $1, $2, $3}' /proc/loadavg
	echo "
#######################
### USERS LOGGED IN ###
#######################"
	echo
	seed=$(w | awk '{printf "%-10s %-10s %-10s\n", $1, $3, $7}' | sed '1d;2d')
	echo "$seed"; echo "
#######################
### USER OPEN FILES ###
#######################"
	echo
	sow=$(lsof -i | awk '{printf "%-10s %-10s %-10s %-10s %-10s\n", $1, $3, $5, $8, $9}')
	echo "$sow"; echo "
#############
### USERS ###
#############"
	echo
	harvest=$(grep "/bin/bash\|/bin/sh\|/bin/ksh\|/bin/zsh\|/bin/ion\|/bin/dash\|/bin/ash" /etc/passwd)
	echo "$harvest"; echo 
}

# Create an "ending" function.
ending() {
	echo -e ""$orng" Have you collected all you need (Yes/No)?"$noc""
	read -p "" -e sunset
	if [ "$sunset" == 'Yes' ] || [ "$sunset" == 'yes' ] || [ "$sunset" == 'Y' ] || [ "$sunset" == 'y' ]; then
	echo
	echo -e ""$orng" Removing evidence of the harvest..."$noc""
	sleep 3s
	rm /tmp/.harvest
	clear
elif [ "$sunset" == 'No' ] || [ "$sunset" == 'no' ] || [ "$sunset" == 'N' ] || [ "$sunset" == 'n' ]; then
	echo
	echo -e ""$orng" I'll allow you 30 seconds to collect...remember to check your /tmp/ directory!"$noc""
	sleep 30s
	echo
	echo -e ""$orng" Time is up!  Your harvest shall be removed..."$noc""
	rm /tmp/.harvest
	clear
else
	echo
	echo -e ""$orng" Ah, a response worthy of removing the harvest..."$noc""
	sleep 3s
	rm /tmp/.harvest
	clear
fi
}

# Create a main function to run all of the functions.
main() {
	pumpkin
	intro
	harvest
	ending
}

# Run the main function.
main

# EOF
